# what is the goal of your workflow
# Goal: whenever someone changes the python code,
# the linter will check if the syantax, format, indentation (linting) is correct or not
name: Auto linter

on: 
  push:
    paths: "*.py"


jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout/clone  the code
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' # Specify your preferred version
      - name: install linter
        run: pip install ruff 
      - name: check the files for linting
        run: ruff check .
      
